OficinaMecanica/OficinaMecanica/Controllers/ClientesController.cs
using OficinaMecanica.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OficinaMecanica.Controllers
{
    public class ClientesController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente cli)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    MeuContexto contexto = new MeuContexto();
                    contexto.Clientes.Add(cli);
                    contexto.SaveChanges();

                    return RedirectToAction("List");
                }
                catch (Exception e)
                {
                    return View(e);
                }
            }

            return View(cli);
        }

        public ActionResult List()
        {
            MeuContexto contexto = new MeuContexto();
            List<Cliente> lista = contexto.Clientes.ToList();

            return View(lista);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);  
            }

            MeuContexto contexto = new MeuContexto();
            Cliente cli = contexto.Clientes.Find(id);

            if (id == null)
            {
                return HttpNotFound();
            }


            return View(cli);
        }


        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(Cliente cli)
        {

            if (ModelState.IsValid)
            {
                MeuContexto contexto = new MeuContexto();
                EditEndereco(cli);
                contexto.Entry(cli).State =
                System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                return RedirectToAction("List");
            }

            return View(cli);
        }

        public void EditEndereco(Cliente cli)
        {
            MeuContexto contexto = new MeuContexto();
            Endereco end = contexto.Enderecos.Where(c => c.EnderecoID.Equals(cli.EnderecoID)).FirstOrDefault();
            end.Rua = cli._Endereco.Rua;
            end.Numero = cli._Endereco.Numero;
            end.Estado = cli._Endereco.Estado;
            end.Bairro = cli._Endereco.Bairro;
            end.CEP = cli._Endereco.CEP;
            contexto.Entry(end).State = System.Data.Entity.EntityState.Modified;
            contexto.SaveChanges();

        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); 
            }

            MeuContexto contexto = new MeuContexto();
            Cliente cli = contexto.Clientes.Find(id);

            if (id == null)
            {
                return HttpNotFound();
            }

            return View(cli);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            try
            {
                MeuContexto contexto = new MeuContexto();
                Cliente cli = contexto.Clientes.Find(id);
                contexto.Clientes.Remove(cli);
                contexto.SaveChanges();
                DeleteEndereco(cli);
                return RedirectToAction("List");
            }
            catch (Exception e)
            {
                return View(e);
            }

        }

        public void DeleteEndereco(Cliente cli)
        {
            MeuContexto contexto = new MeuContexto();
            Endereco serie = contexto.Enderecos.Where(c => c.EnderecoID.Equals(cli.EnderecoID)).FirstOrDefault();
            contexto.Enderecos.Remove(serie);
            contexto.SaveChanges();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);  
            }

            MeuContexto contexto = new MeuContexto();
            Cliente cli = contexto.Clientes.Find(id);

            if (id == null)
            {
                return HttpNotFound();
            }

            return View(cli);
        }

    }

}

OficinaMecanica/OficinaMecanica/Controllers/OrdemServicosController.cs
using OficinaMecanica.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.Collections.Generic;

namespace OficinaMecanica.Controllers
{
    public class OrdemServicosController : Controller
    {

        public MeuContexto Contexto = new MeuContexto();

        public OrdemServicosController()
        {

        }

        public ActionResult Index()
        {


            var ordemServicos = this.Contexto.OrdemServicos.ToList();
            var situacoes = this.Contexto.Situacaos.ToList();
            
            var model = new OrdemServicoViewModels (ordemServicos, situacoes);

            return View(model);
        }


        public ActionResult Create()
        {



            ViewBag.SituacaoID = new SelectList(
            this.Contexto.Situacaos.ToList(),
            "SituacaoID",
            "Nome"
             );

            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrdemServico ordemServico, string situacaoId)
        {
            if (ModelState.IsValid)
            {

                this.Contexto.OrdemServicos.Add(ordemServico);
                this.Contexto.SaveChanges();
                return RedirectToAction("List");
            }

            ViewBag.SituacaoID = new SelectList(
            this.Contexto.Situacaos.ToList(),
            "SituacaoID",
            "Nome",
            situacaoId
             );


            return View(ordemServico);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MeuContexto contexto = new MeuContexto();

            OrdemServico os = contexto.OrdemServicos.Find(id);

            if (os == null)
            {
                return HttpNotFound();
            }

            return View(os);
        }
        public ActionResult Edit(int? id)
        {
            var ordemServico = this.Contexto.OrdemServicos.FirstOrDefault(_ => _.OrdemServicoID == id);
            var situacao = this.Contexto.Situacaos.ToList();
            

            ViewBag.SituacaoID = new SelectList(
                this.Contexto.Situacaos.ToList(),
                "SituacaoID",
                "Nome"
                );

            

            var model = new EditViewModels(ordemServico, situacao);

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrdemServico ordemServico, string situacaoId)
        {
            if (ModelState.IsValid)
            {
                ordemServico.SituacaoID = int.Parse(situacaoId);
               

                this.Contexto.Entry(ordemServico).State = EntityState.Modified;
                this.Contexto.SaveChanges();
                return RedirectToAction("List");
            }

            ViewBag.SituacaoID = new SelectList(
               this.Contexto.Situacaos.ToList(),
               "SituacaoID",
               "Nome",
              situacaoId
               );

            return View(ordemServico);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }



            OrdemServico os = Contexto.OrdemServicos.Find(id);
            if (os == null)
            {
                return HttpNotFound();
            }

            return View(os);

        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            OrdemServico os = Contexto.OrdemServicos.Find(id);

            this.Contexto.OrdemServicos.Remove(os);
            this.Contexto.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult BuscaPorPlaca()
        {
            Session["lista"] = null;
            return View();
        }

        [HttpPost]
        public ActionResult BuscaPorPlaca(string nome)
        {
            MeuContexto contexto = new MeuContexto();
            var serie = contexto.OrdemServicos.Where(c => c.Placa.ToLower().Equals(nome.ToLower()));
            List<OrdemServico> lista = serie.ToList();
            ViewBag.Lista = lista;
            if (lista.Count > 0)
            {
                Session["lista"] = serie;
            }
            else
            {
                Session["lista"] = null;
                ViewBag.Message = "Nada encontrado no sistema com a placa : " + nome;
            }

            return View();
        }

    }
}

OficinaMecanica/OficinaMecanica/Controllers/ServicosController.cs
using OficinaMecanica.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OficinaMecanica.Controllers
{
    public class ServicosController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Servico servico)
        {
            if (ModelState.IsValid)
            {
                MeuContexto contexto = new MeuContexto();
                contexto.Servicos.Add(servico);
                contexto.SaveChanges();
                return RedirectToAction("List");
            }
            return View(servico);
        }

        public ActionResult List()
        {

            MeuContexto contexto = new MeuContexto();

            List<Servico> lista = contexto.Servicos.ToList();

            return View(lista);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MeuContexto contexto = new MeuContexto();

            Servico ser = contexto.Servicos.Find(id);

            if (ser == null)
            {
                return HttpNotFound();
            }

            return View(ser);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MeuContexto contexto = new MeuContexto();

            Servico ser = contexto.Servicos.Find(id);

            if (ser == null)
            {
                return HttpNotFound();
            }

            return View(ser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Servico ser)
        {
            if (ModelState.IsValid)
            {
                MeuContexto contexto = new MeuContexto();
                contexto.Entry(ser).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                return RedirectToAction("List");
            }
            return View(ser);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MeuContexto contexto = new MeuContexto();

            Servico ser = contexto.Servicos.Find(id);
            if (ser == null)
            {
                return HttpNotFound();
            }

            return View(ser);

        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MeuContexto contexto = new MeuContexto();
            Servico ser= contexto.Servicos.Find(id);

            contexto.Servicos.Remove(ser);
            contexto.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

OficinaMecanica/OficinaMecanica/Controllers/SituacoesController.cs
using OficinaMecanica.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OficinaMecanica.Controllers
{
    public class SituacoesController : Controller
    {
        // GET: Editoras
        public ActionResult Index()
    {

        MeuContexto contexto = new MeuContexto();

        List<Situacao> situacoes = contexto.Situacaos.ToList();

        return View(situacoes);
    }
    public ActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Situacao situacao)
    {
        if (ModelState.IsValid)
        {
            MeuContexto contexto = new MeuContexto();
            contexto.Situacaos.Add(situacao);
            contexto.SaveChanges();
            return RedirectToAction("List");
        }
        return View(situacao);
    }

    public ActionResult Details(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        MeuContexto contexto = new MeuContexto();

        Situacao sit = contexto.Situacaos.Find(id);

        if (sit == null)
        {
            return HttpNotFound();
        }

        return View(sit);
    }
    public ActionResult Edit(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        MeuContexto contexto = new MeuContexto();

        Situacao sit = contexto.Situacaos.Find(id);

        if (sit == null)
        {
            return HttpNotFound();
        }

        return View(sit);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(Situacao sit)
    {
        if (ModelState.IsValid)
        {
            MeuContexto contexto = new MeuContexto();
            contexto.Entry(sit).State = System.Data.Entity.EntityState.Modified;
            contexto.SaveChanges();
            return RedirectToAction("List");
        }
        return View(sit);
    }
    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        MeuContexto contexto = new MeuContexto();

        Situacao sit = contexto.Situacaos.Find(id);
        if (sit == null)
        {
            return HttpNotFound();
        }

        return View(sit);

    }


    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
        MeuContexto contexto = new MeuContexto();
        Situacao sit = contexto.Situacaos.Find(id);

        contexto.Situacaos.Remove(sit);
        contexto.SaveChanges();
        return RedirectToAction("List");
    }
}
}

OficinaMecanica/OficinaMecanica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BrOficina", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

                 <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                  @if (Request.IsAuthenticated)
                   {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clientes <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
 
                                <li>@Html.ActionLink("Novo Cadastro", "Create", "Clientes")</li>
                                <li>@Html.ActionLink("Lista de Clientes", "List", "Clientes")</li>

                        </ul>
                    </li>
                   }

                   @if (Request.IsAuthenticated)
                    {
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Funcionarios <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                             
                                <li>@Html.ActionLink("Novo Funcionario", "Create", "Funcionarios")</li>
                                <li>@Html.ActionLink("Lista de Funcionários", "List","Funcionarios")</li>
                              
                        </ul>
                     </li>
                    }


                   @if (Request.IsAuthenticated)
                    {
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Serviços <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">

                            <li>@Html.ActionLink("Novo Serviço", "Create", "Servicos")</li>
                            <li>@Html.ActionLink("Lista de Seviços", "List", "Servicos")</li>

                        </ul>
                     </li>
                    }

                        
                   @if (Request.IsAuthenticated)
                    {
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Ordem de Serviços <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                             
                                <li>@Html.ActionLink("Nova Ordem de Serviço", "Create", "OrdemServicos")</li>
                                <li>@Html.ActionLink("Lista de OS", "List", "OrdemServicos")</li>
                                <li>@Html.ActionLink("Busca por placa", "BuscaPorPlaca", "OrdemServicos")</li>
                        </ul>
                     </li>
                    }

                        @if (Request.IsAuthenticated)
                    {
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Situação <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                             
                                <li>@Html.ActionLink("Nova Situação", "Create", "Situacoes")</li>
                                <li>@Html.ActionLink("Lista de situações", "List", "Situacoes")</li>
                        </ul>
                     </li>
                    }

                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>